# Generated by Django 3.1.7 on 2021-03-16 16:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('dateTime', models.DateTimeField()),
                ('speaker', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=350)),
                ('type', models.CharField(choices=[('T', 'Technology'), ('M', 'Marketing'), ('N', 'Networking'), ('C', 'Career')], default='T', max_length=1)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
